### PR TITLE
Fail fast on invalid config regexes and enabled config

### LINKED ISSUE #403: Panicking .expect() on regex compilation from user configuration
## Summary

Configuration-derived regex patterns use `.expect()` which will panic at runtime if the pattern is invalid. If `handler.path` or integration config contains invalid regex metacharacters and validation is bypassed (env override, manual TOML edit), the service crashes on first matching request.

## Refs

- `crates/common/src/settings.rs` line 255 — `Regex::new(&self.path).expect(...)`
- `crates/common/src/integrations/nextjs/script_rewriter.rs` line 125 — `Regex::new(&pattern).expect(...)`
- `crates/common/src/integrations/nextjs/script_rewriter.rs` line 141 — `Regex::new(&pattern).expect(...)`
- `crates/common/src/integrations/nextjs/shared.rs` line 83 — `Regex::new(...).expect(...)`

## Recommendation

Return `Result` from these constructors; catch at startup with a descriptive error message.

## Context

Production readiness audit — see #396

### PR DESCRIPTION
**Pull request by prk-Jr**
## Summary

- Fail startup instead of panicking or silently disabling when config-derived regexes or enabled integration/provider configs are invalid.
- Prepare handler and Next.js rewrite artifacts before request handling so invalid config returns descriptive `TrustedServerError` responses.
- Add regression coverage for handler overrides, disabled-config bypasses, Next.js RSC/`__NEXT_DATA__` rewrites, and publisher fallback encoding behavior.

## Changes

| File | Change |
| ---- | ------ |
| `.claude/agents/pr-creator.md` | Require PRs touching config-derived regex or pattern compilation to document startup hardening and validation coverage. |
| `.claude/agents/pr-reviewer.md` | Treat panic-prone config compilation and silent invalid-enabled-config disablement as blocking review findings. |
| `crates/common/src/auction/mod.rs` | Make auction provider construction fallible and propagate startup configuration errors. |
| `crates/common/src/auth.rs` | Make basic-auth evaluation fallible so invalid handler regexes return config errors instead of panicking. |
| `crates/common/src/integrations/adserver_mock.rs` | Return startup errors for invalid enabled provider config instead of logging and skipping it. |
| `crates/common/src/integrations/aps.rs` | Return startup errors for invalid enabled provider config instead of logging and skipping it. |
| `crates/common/src/integrations/datadome.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/didomi.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/google_tag_manager.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/gpt.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/lockr.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/mod.rs` | Update shared integration builder signatures and helpers for fallible startup registration. |
| `crates/common/src/integrations/nextjs/html_post_process.rs` | Pass request host and scheme through the post-processor RSC rewrite path. |
| `crates/common/src/integrations/nextjs/mod.rs` | Build Next.js rewriters during registration and add fixture-style regressions for RSC and `__NEXT_DATA__` coverage. |
| `crates/common/src/integrations/nextjs/rsc.rs` | Reuse the new RSC rewrite helpers while preserving payload sizing and chunk handling. |
| `crates/common/src/integrations/nextjs/script_rewriter.rs` | Replace config-derived `expect()` regex compilation with fallible rewriters and add hostname, port, whitespace, and metacharacter regressions. |
| `crates/common/src/integrations/nextjs/shared.rs` | Replace origin-specific regex construction with static generic patterns and safe hostname-boundary helpers. |
| `crates/common/src/integrations/permutive.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/integrations/prebid.rs` | Fail startup on invalid enabled config, including empty `server_url`, and return fallible provider builders. |
| `crates/common/src/integrations/registry.rs` | Propagate integration registration errors during startup instead of silently dropping invalid enabled integrations. |
| `crates/common/src/integrations/testlight.rs` | Make enabled config registration fail fast with descriptive validation errors. |
| `crates/common/src/publisher.rs` | Restrict publisher fallback `Accept-Encoding` to codecs the rewrite pipeline supports and add regression coverage. |
| `crates/common/src/settings.rs` | Add runtime preparation for handler regexes, short-circuit raw `enabled = false` configs, and add startup hardening regressions. |
| `crates/common/src/settings_data.rs` | Run runtime preparation when loading baked settings data so invalid handler regexes fail during startup. |
| `crates/fastly/src/main.rs` | Surface orchestrator and auth configuration errors through the existing Fastly error-response path. |

## Hardening note

Invalid `handlers[].path` regexes now fail during startup preparation and still return descriptive configuration errors if request-time code encounters unprepared settings. Enabled integrations and auction providers now fail registry/orchestrator startup instead of logging and disabling themselves, while raw `enabled = false` configs still short-circuit before validation. Regression coverage includes invalid handler TOML and env overrides, disabled-invalid config bypasses, enabled-invalid integration/provider startup failures, empty `prebid.server_url`, Next.js `__NEXT_DATA__` and RSC hostname/port/metacharacter rewrites, and the publisher fallback encoding path.

## Closes

Closes #403

## Test plan

- [x] `cargo test --workspace`
- [x] `cargo clippy --all-targets --all-features -- -D warnings`
- [x] `cargo fmt --all -- --check`
- [x] JS tests: `cd crates/js/lib && npx vitest run`
- [x] JS format: `cd crates/js/lib && npm run format`
- [x] Docs format: `cd docs && npm run format`
- [ ] WASM build: `cargo build --bin trusted-server-fastly --release --target wasm32-wasip1`
- [ ] Manual testing via `fastly compute serve`
- [x] Other: `npx vitest run` was skipped per explicit user instruction because of the unrelated repo-wide `ERR_REQUIRE_ESM` failure in `html-encoding-sniffer`.

## Checklist

- [x] Changes follow [CLAUDE.md](/CLAUDE.md) conventions
- [x] No `unwrap()` in production code — use `expect(\"should ...\")`
- [x] Uses `tracing` macros (not `println!`)
- [x] New code has tests
- [x] No secrets or credentials committed

### CODE REVIEW

File: crates/common/src/publisher.rs [hunk 1]
```diff
@@ -15,6 +15,13 @@ use crate::streaming_processor::{Compression, PipelineConfig, StreamProcessor, S
 use crate::streaming_replacer::create_url_replacer;
 use crate::synthetic::get_or_generate_synthetic_id;
 
+/// Encodings supported by the publisher response rewrite pipeline.
+const SUPPORTED_ENCODINGS: &str = "gzip, deflate, br";
```
Comment (aram356) [inline crates/common/src/publisher.rs]: 🤔 **thinking** — `restrict_accept_encoding` unconditionally overwrites client preferences

The fix correctly prevents the pipeline from receiving encodings it can't decode (e.g., zstd). But a client that only accepts `identity` or a strict subset will now receive content encoded with gzip/br it didn't ask for.

Consider computing the intersection of client capabilities and pipeline capabilities, falling back to `identity` if the intersection is empty.

File: crates/common/src/integrations/nextjs/script_rewriter.rs [hunk 2]
```diff
@@ -62,8 +71,14 @@ impl IntegrationScriptRewriter for NextJsNextDataRewriter {
     }
 }
 
-fn rewrite_nextjs_values_with_rewriter(content: &str, rewriter: &UrlRewriter) -> Option<String> {
-    rewriter.rewrite_embedded(content)
+fn rewrite_nextjs_values_with_rewriter(
```
Comment (aram356) [inline crates/common/src/integrations/nextjs/script_rewriter.rs]: ♻️ **refactor** — `rewrite_nextjs_values_with_rewriter` is a pass-through wrapper

This function just delegates to `rewriter.rewrite_embedded(...)` with no additional logic. The call site in `rewrite_structured` (line 42) could call `self.rewriter.rewrite_embedded(...)` directly and this intermediary could be removed.

File: crates/common/src/settings.rs [hunk 3]
```diff
@@ -411,10 +471,14 @@ fn validate_no_trailing_slash(value: &str) -> Result<(), ValidationError> {
 }
 
 fn validate_path(value: &str) -> Result<(), ValidationError> {
```
Comment (aram356) [inline crates/common/src/settings.rs]: ♻️ **refactor** — `validate_path` compiles the regex a second time

`validate_path` compiles the regex during serde validation, then `prepare_runtime()` → `compiled_regex()` compiles it again into the `OnceLock`. Since `from_toml` now calls `prepare_runtime()`, the validation-time compile is redundant work.

Consider deferring regex validation to `prepare_runtime` only and removing the `validate_path` custom validator (or having `validate_path` just check non-empty, letting `prepare_runtime` handle compilation).

File: crates/common/src/settings.rs [hunk 4]
```diff
@@ -136,6 +136,13 @@ impl IntegrationSettings {
         }
     }
 
+    fn is_explicitly_disabled(raw: &JsonValue) -> bool {
```
Comment (aram356) [inline crates/common/src/settings.rs]: 🤔 **thinking** — `is_explicitly_disabled` edge case with non-bool `enabled`

If someone writes `"enabled": "false"` (string instead of bool), `as_bool()` returns `None`, so the integration proceeds to deserialization and may fail validation. This is correct behavior (malformed config should fail), but worth noting that the bypass only fires for the literal JSON boolean `false`.

Also worth noting: integrations that default `enabled` to `true` with no `enabled` field in the config will correctly proceed to validation, which is the desired behavior.

File: crates/common/src/publisher.rs [hunk 5]
```diff
@@ -15,6 +15,83 @@ use crate::streaming_processor::{Compression, PipelineConfig, StreamProcessor, S
...
+                continue;
+            };
+            if name.trim().eq_ignore_ascii_case("q") {
+                if let Ok(parsed_qvalue) = value.trim().parse::<f32>() {
+                    qvalue = parsed_qvalue;
+                }
+            }
+        }
+
+        matched_qvalue = Some(qvalue);
```
Comment (aram356) [inline crates/common/src/publisher.rs]: ♻️ **refactor** — `accept_encoding_qvalue` returns the last match, not the first

If `Accept-Encoding` contains a duplicate token (e.g., `gzip;q=1, gzip;q=0`), this returns the **last** match's qvalue. Most HTTP implementations use first-match semantics.

**Suggestion**:
```rust
matched_qvalue = Some(qvalue);
break; // first match wins per RFC convention
```

In practice duplicate tokens are rare and unlikely to cause issues, but first-match is more conventional.

File: crates/common/src/publisher.rs [hunk 6]
```diff
@@ -15,6 +15,83 @@ use crate::streaming_processor::{Compression, PipelineConfig, StreamProcessor, S
...
+    else {
+        return;
+    };
+    req.set_header(
+        header::ACCEPT_ENCODING,
+        select_supported_accept_encoding(Some(current)),
+    );
+}
+
+fn select_supported_accept_encoding(client_accept_encoding: Option<&str>) -> String {
```
Comment (aram356) [inline crates/common/src/publisher.rs]: ♻️ **refactor** — `select_supported_accept_encoding(None)` is dead code

The only caller `restrict_accept_encoding` returns early when `Accept-Encoding` is absent, so the `None` branch (returning `"identity"`) is unreachable. You could simplify the parameter to `&str` if this function isn't intended for other callers.

File: crates/common/src/integrations/nextjs/shared.rs [hunk 7]
```diff
@@ -2,19 +2,31 @@
...
     Regex::new(
         r#"(?s)(?:(?:self|window)\.__next_f\.push|\(\s*(?:self|window)\.__next_f\s*=\s*(?:self|window)\.__next_f\s*\|\|\s*\[\]\s*\)\s*\.push)\(\[\s*1\s*,\s*(['"])"#,
     )
     .expect("valid RSC push call regex")
 });
 
+/// Generic URL pattern for RSC payload rewriting.
+pub(crate) static RSC_URL_PATTERN: LazyLock<Regex> = LazyLock::new(|| {
+    Regex::new(
+        r#"(https?)?(:)?(\\\\\\\\\\\\\\\\//|\\\\\\\\//|\\/\\/|//)(?P<host>\[[^\]]+\](?::\d+)?|[^/"'\\\s?#<>,)]+)"#,
```
Comment (aram356) [inline crates/common/src/integrations/nextjs/shared.rs]: 🌱 **seedling** — Host capture group `[^/"'\\\s?#<>,)]+` is very permissive

This character class matches anything not in the exclusion set, which could theoretically match non-hostname content in unusual payloads. Currently safe because `strip_origin_host_with_optional_port` filters properly, but worth keeping an eye on if RSC payload formats evolve.

File: crates/trusted-server-core/src/settings.rs [hunk 8]
```diff
@@ -467,13 +527,24 @@ impl Settings {
...
+    ///
+    /// Returns [`TrustedServerError::Configuration`] if any handler has an invalid path regex.
+    pub(crate) fn uncovered_admin_endpoints(
+        &self,
+    ) -> Result<Vec<&'static str>, Report<TrustedServerError>> {
+        let mut uncovered = Vec::new();
+        for &path in Self::ADMIN_ENDPOINTS {
+            let covered = self
+                .handlers
+                .iter()
```
[the remark this answers is not in the document]
Comment (prk-Jr) [reply crates/trusted-server-core/src/settings.rs]: Replaced with a `for` loop that breaks on first match.

**Review by ChristianPavilonis — APPROVED** [review]
Looks good
