### PR TITLE
Fix weak and inconsistent secret default validation

### LINKED ISSUE #406: Weak/inconsistent secret default validation
## Summary

Only `synthetic.secret_key` is checked against the literal `"secret-key"`. `publisher.proxy_secret` defaults to `"change-me-proxy-secret"` and `synthetic.secret_key` defaults to `"trusted-server"` — neither is caught by the single check. A deployment using defaults has predictable encryption keys.

## Refs

- `trusted-server.toml` line 10 — `proxy_secret = "change-me-proxy-secret"`
- `trusted-server.toml` line 15 — `secret_key = "trusted-server"`
- `crates/common/src/settings.rs` line 197 — `Settings::validate()` — no proxy_secret check
- `crates/common/src/settings_data.rs` line 37 — only checks `== "secret-key"`

## Recommendation

Reject all known placeholder values for both secrets. Consider minimum entropy requirements.

## Context

Production readiness audit — see #396

### PR DESCRIPTION
**Pull request by ChristianPavilonis**
## Summary

- **Reject all known placeholder values** for `synthetic.secret_key` (`"secret-key"`, `"secret_key"`, `"trusted-server"`) and `publisher.proxy_secret` (`"change-me-proxy-secret"`) at runtime startup so misconfigured deployments fail fast.
- **Consolidate validation** into predicate methods (`is_placeholder_secret_key`, `is_placeholder_proxy_secret`) with explicit placeholder lists, replacing the inconsistent checks that missed the actual TOML defaults.
- **Improve error reporting** by renaming `InsecureSecretKey` to `InsecureDefault { field }` so the error message identifies which secret triggered rejection.

## Changes

| File | Change |
| ---- | ------ |
| `crates/common/src/error.rs` | Renamed `InsecureSecretKey` → `InsecureDefault { field: String }` with a descriptive display message |
| `crates/common/src/settings.rs` | Added `PROXY_SECRET_PLACEHOLDERS` const + `is_placeholder_proxy_secret()` on `Publisher`; replaced `validate_secret_key()` with `SECRET_KEY_PLACEHOLDERS` const + `is_placeholder_secret_key()` on `Synthetic`; added 4 unit tests |
| `crates/common/src/settings_data.rs` | Replaced single `== "secret-key"` check with calls to both predicates; returns field-specific `InsecureDefault` errors; updated test to assert placeholder rejection |
| `crates/common/build.rs` | Added comment explaining why placeholder rejection is intentionally skipped at build time |

## Closes

Closes #406

## Test plan

- [x] `cargo test --workspace`
- [x] `cargo clippy --all-targets --all-features -- -D warnings`
- [x] `cargo fmt --all -- --check`

## Checklist

- [x] Changes follow [CLAUDE.md](/CLAUDE.md) conventions
- [x] No `unwrap()` in production code — use `expect("should ...")`
- [x] Uses `tracing` macros (not `println!`)
- [x] New code has tests
- [x] No secrets or credentials committed

### CODE REVIEW

File: crates/common/src/settings_data.rs [hunk 1]
```diff
@@ -34,8 +34,17 @@ pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
             message: "Failed to validate configuration".to_string(),
         })?;
 
-    if settings.synthetic.secret_key == "secret-key" {
-        return Err(Report::new(TrustedServerError::InsecureSecretKey));
+    // Reject known placeholder values for secrets that feed into cryptographic operations.
+    if Synthetic::is_placeholder_secret_key(&settings.synthetic.secret_key) {
```
Comment (aram356) [inline crates/common/src/settings_data.rs]: **LOW — Only the first insecure field is reported**

The two placeholder checks are sequential early returns. If both `secret_key` and `proxy_secret` are placeholders (the default state from `trusted-server.toml`), the operator only sees the `synthetic.secret_key` error and must fix-and-redeploy to discover the `proxy_secret` error.

Collect all violations and report them in a single error to reduce fix/redeploy cycles.

File: crates/common/src/settings.rs [hunk 2]
```diff
@@ -27,6 +27,17 @@ pub struct Publisher {
 }
 
 impl Publisher {
+    /// Known placeholder values that must not be used in production.
+    #[allow(dead_code)]
```
Comment (aram356) [inline crates/common/src/settings.rs]: **NIT — Spurious `#[allow(dead_code)]` on public items**

Both the constants and the `is_placeholder_*` methods are `pub` and called from `settings_data.rs`. They are not dead code. The `#[allow(dead_code)]` suppresses nothing and misleads readers into thinking these items might be unused.

**Review by aram356 — COMMENTED** [review]
## Summary

Centralizes placeholder-secret rejection into `Settings::reject_placeholder_secrets()`, adds `proxy_secret` validation, and makes tests deterministic. Addresses all findings from the previous review round.

## Blocking

### 🔧 wrench

- **Removed `test_get_settings` smoke test not replaced**: The original `test_get_settings` was the only test exercising the full `get_settings()` end-to-end path (embedded bytes → UTF-8 → parse → validate → placeholder check). The new tests only exercise `Settings::from_toml()` + `reject_placeholder_secrets()` directly. A regression in the glue code would go undetected. (`settings_data.rs`)

### ❓ question

- **`toml_with_secrets` replacement is fragile and can silently no-op**: `str::replace()` returns the original string unchanged if the pattern doesn't match. If `crate_test_settings_str()` changes quoting or default values, replacements silently do nothing. The `accepts_non_placeholder_secrets` test is especially vulnerable — both old and new values are non-placeholders, so it passes even if replacement fails. (`settings_data.rs:56-66`)

## Non-blocking

### 🤔 thinking

- **Case-sensitive placeholder matching**: `"Secret-Key"` or `"SECRET-KEY"` bypasses the check while still being predictable. Consider `eq_ignore_ascii_case`. (`settings.rs:205-207`)

### 🌱 seedling

- **Minimum length for crypto secrets**: `min = 1` prevents empty but `"x"` still passes validation then feeds into `Sha256::digest` for XChaCha20-Poly1305 key derivation. Consider `min = 16` as a follow-up. (`settings.rs:27, 194`)

### ⛏ nitpick

- **Double space in doc comment**: `"...offending field.  This centralises..."` — rest of codebase uses single space. (`settings.rs:388`)

## CI Status

- fmt: PASS
- clippy: PASS  
- rust tests: PASS
- js tests: PASS
- CodeQL: FAIL (appears infrastructure-related, not caused by this PR)

File: crates/common/src/settings_data.rs [hunk 3]
```diff
@@ -49,22 +48,80 @@ pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
...
+                r#"secret_key = "test-secret-key""#,
+                &format!(r#"secret_key = "{secret_key}""#),
+            )
+            .replace(
+                r#"proxy_secret = "unit-test-proxy-secret""#,
+                &format!(r#"proxy_secret = "{proxy_secret}""#),
+            )
+    }
 
     #[test]
```
Comment (aram356) [inline crates/common/src/settings_data.rs]: 🔧 **wrench** — The original `test_get_settings` was the only test exercising the full `get_settings()` end-to-end (embedded bytes → UTF-8 → parse → validate → placeholder check). The new tests only call `Settings::from_toml()` + `reject_placeholder_secrets()` directly.

Consider adding back a smoke test:

```rust
#[test]
fn get_settings_loads_embedded_config() {
    let settings = super::get_settings();
    assert!(settings.is_ok(), "should load settings from embedded TOML");
}
```

File: crates/common/src/settings_data.rs [hunk 4]
```diff
@@ -49,22 +48,80 @@ pub fn get_settings() -> Result<Settings, Report<TrustedServerError>> {
 
 #[cfg(test)]
 mod tests {
-    use super::*;
+    use crate::error::TrustedServerError;
+    use crate::settings::Settings;
+    use crate::test_support::tests::crate_test_settings_str;
+
+    /// Builds a TOML string with the given secret values swapped in.
+    fn toml_with_secrets(secret_key: &str, proxy_secret: &str) -> String {
```
Comment (aram356) [inline crates/common/src/settings_data.rs]: ❓ **question** — `str::replace()` returns the original string unchanged if the pattern doesn't match. If `crate_test_settings_str()` ever changes quoting or default values, these replacements silently no-op.

The `accepts_non_placeholder_secrets` test is especially vulnerable: it replaces `"test-secret-key"` with `"production-secret-key"` — both non-placeholders — so even if replacement fails, the test passes.

Consider asserting the replacement actually took effect:

```rust
fn toml_with_secrets(secret_key: &str, proxy_secret: &str) -> String {
    let original = crate_test_settings_str();
    let result = original
        .replace(/* ... */)
        .replace(/* ... */);
    assert_ne!(result, original, "should have replaced at least one secret value");
    result
}
```

File: crates/common/src/settings.rs [hunk 5]
```diff
@@ -180,23 +190,20 @@ impl DerefMut for IntegrationSettings {
...
-            _ => Ok(()),
-        }
+    /// Known placeholder values that must not be used in production.
+    pub const SECRET_KEY_PLACEHOLDERS: &[&str] = &["secret-key", "secret_key", "trusted-server"];
+
+    /// Returns `true` if `secret_key` matches a known placeholder value.
+    #[must_use]
+    pub fn is_placeholder_secret_key(secret_key: &str) -> bool {
+        Self::SECRET_KEY_PLACEHOLDERS.contains(&secret_key)
     }
```
Comment (aram356) [inline crates/common/src/settings.rs]: 🤔 **thinking** — Placeholder matching is case-sensitive. Someone setting `secret_key = "Secret-Key"` bypasses the check while still using a predictable value. Consider case-insensitive matching:

```rust
pub fn is_placeholder_secret_key(secret_key: &str) -> bool {
    Self::SECRET_KEY_PLACEHOLDERS
        .iter()
        .any(|p| p.eq_ignore_ascii_case(secret_key))
}
```

File: crates/common/src/settings.rs [hunk 6]
```diff
@@ -377,6 +384,33 @@ impl Settings {
         Ok(settings)
     }
 
+    /// Checks all secret fields for known placeholder values and returns an
+    /// error listing every offending field.  This centralises the placeholder
```
Comment (aram356) [inline crates/common/src/settings.rs]: ⛏ **nitpick** — Double space after period: `"field.  This"` → `"field. This"`

File: crates/common/src/settings.rs (hunk 5 above)
Comment (ChristianPavilonis) [reply crates/common/src/settings.rs]: Done — both `is_placeholder_secret_key` and `is_placeholder_proxy_secret` now use `eq_ignore_ascii_case`.
