### PR TITLE
Fix key rotation

### LINKED ISSUE #185: Request signing key rotation no longer works

### PR DESCRIPTION
**Pull request by ChristianPavilonis**
Previously using hardcoded backend names, we later added port number to the dynamic backend names which broke the key rotation.

Now the fastly client will use the generated backend name.

closes #185

### CODE REVIEW

File: crates/common/src/fastly_storage.rs [hunk 1]
```diff
@@ -93,9 +94,12 @@ impl FastlyApiClient {
         let secret_store = FastlySecretStore::new(store_name);
         let api_key = secret_store.get(key_name)?;
 
+        log::info!("FastlyApiClient initialized with backend: {}", backend_name);
+
         Ok(Self {
             api_key,
             base_url: "https://api.fastly.com".to_string(),
```
Comment (aram356) [inline crates/common/src/fastly_storage.rs]: ⛏️ Use const for "https://api.fastly.com"

File: docs/guide/key-rotation.md [hunk 2]
```diff
@@ -26,6 +26,174 @@ Key rotation is the process of generating new signing keys and transitioning fro
...
+    format = "inline-toml"
+    [local_server.config_stores.jwks_store.contents]
+      ts-2025-01-01 = "{\"kty\":\"OKP\",\"crv\":\"Ed25519\",\"kid\":\"ts-2025-01-01\",\"use\":\"sig\",\"x\":\"...\"}"
+      current-kid = "ts-2025-01-01"
+      active-kids = "ts-2025-01-01"
+
+[local_server.secret_stores]
+  [[local_server.secret_stores.signing_keys]]
+    key = "ts-2025-01-01"
+    data = "NVnTYrw5xoyTJDOwoUWoPJO3A6UCCXOJJUzgGTxxx7k="
```
Comment (aram356) [inline docs/guide/key-rotation.md]: ⛏️ Use placeholder in place actual key
